import { NextResponse } from 'next/server'
import { headers } from 'next/headers'
import { getPayload } from 'payload'
import config from '@payload-config'
import { z } from 'zod/v4'
import { rateLimit } from '@/lib/rate-limit'
import { getClientIp } from '@/lib/client-ip'
import { recalculerEtAppliquerPalier } from '@/lib/groupes'
import { groupeCreatedEmail } from '@/lib/emails'
import { sendEmail } from '@/lib/email-sender'
import { hashUserId } from '@/lib/audit'

const bodySchema = z.object({
  nom: z.string().min(1).max(120),
})

export async function POST(request: Request) {
  // Rate limit: 10 req/min/IP
  const ip = getClientIp(request.headers)
  const { success: allowed } = rateLimit(`groupes-create:${ip}`, { limit: 10, windowMs: 60_000 })
  if (!allowed) {
    return NextResponse.json({ error: 'Trop de requetes' }, { status: 429 })
  }

  const hdrs = await headers()
  const payload = await getPayload({ config })
  const { user } = await payload.auth({ headers: hdrs })

  if (!user) {
    return NextResponse.json({ error: 'Non authentifie' }, { status: 401 })
  }

  const body = await request.json().catch(() => null)
  const parsed = bodySchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: 'Parametres invalides' }, { status: 400 })
  }

  // Read fresh user from DB
  const freshUser = await payload.findByID({
    collection: 'users',
    id: user.id,
    overrideAccess: true,
  })

  // Must not already belong to a groupe
  if (freshUser.groupe) {
    return NextResponse.json(
      { error: 'Vous appartenez deja a un groupe' },
      { status: 400 },
    )
  }

  // Fonctionnalite groupes/affiliation DORMANTE (ADR-0009) : aucun point
  // d'entree UI expose au grand public, conservee pour l'exploitation/support
  // admin (ADR-0009 §5). L'ancien gate "plan Infinite" n'existe plus dans le
  // modele 3-entites (ADR-0011) et rendait la route structurellement
  // inaccessible (403 pour tout le monde, y compris l'admin) : on la
  // realigne sur un gate admin, coherent avec l'intention "reservee a
  // l'exploitation" sans reactiver la feature au public.
  if (freshUser.role !== 'admin') {
    return NextResponse.json(
      { error: 'La creation d\'un groupe est reservee a l\'administration' },
      { status: 403 },
    )
  }

  try {
    // 1. Create the groupe (code auto-generated by beforeValidate hook)
    const groupe = await payload.create({
      collection: 'groupes',
      data: {
        nom: parsed.data.nom,
        owner: user.id,
        code: '', // placeholder, replaced by hook
        palierActuel: '0',
      },
      overrideAccess: true,
    })

    // 2. Attach the user to the new groupe
    await payload.update({
      collection: 'users',
      id: user.id,
      data: { groupe: groupe.id },
      overrideAccess: true,
    })

    // 3. Recalculate palier (will be 0 for a single member, but ensures consistency)
    await recalculerEtAppliquerPalier(payload, groupe.id)

    // 4. Audit-log RGPD : trace persistante de la creation du groupe.
    try {
      await payload.create({
        collection: 'audit-logs',
        data: {
          type: 'groupe_created',
          userIdHash: hashUserId(user.id),
          metadata: {
            groupeId: String(groupe.id),
            groupeCode: groupe.code,
            groupeNom: groupe.nom,
          },
        },
        overrideAccess: true,
      })
    } catch (err) {
      console.error('[groupes/create] audit-log groupe_created failed:', err)
    }

    // 5. Confirmation email to the owner with the shareable code
    await sendEmail({
      payload,
      kind: 'group-created',
      to: freshUser.email,
      subject: `Panorama Pub — Votre groupe ${groupe.nom} est cree`,
      html: groupeCreatedEmail(freshUser.nomSociete, groupe.nom, groupe.code),
      userId: freshUser.id,
    })

    return NextResponse.json({
      id: groupe.id,
      code: groupe.code,
      nom: groupe.nom,
    })
  } catch (err) {
    console.error('[groupes/create] Erreur:', err)
    return NextResponse.json(
      { error: 'Erreur lors de la creation du groupe' },
      { status: 500 },
    )
  }
}
