/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    reseauteurs: Reseauteur;
    reseaux: Reseau;
    evenements: Evenement;
    inscriptions: Inscription;
    partenaires: Partenaire;
    'licences-packs': LicencesPack;
    'licences-activations': LicencesActivation;
    categories: Category;
    'types-evenement': TypesEvenement;
    badges: Badge;
    groupes: Groupe;
    testimonials: Testimonial;
    'audit-logs': AuditLog;
    'stripe-events': StripeEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    reseauteurs: ReseauteursSelect<false> | ReseauteursSelect<true>;
    reseaux: ReseauxSelect<false> | ReseauxSelect<true>;
    evenements: EvenementsSelect<false> | EvenementsSelect<true>;
    inscriptions: InscriptionsSelect<false> | InscriptionsSelect<true>;
    partenaires: PartenairesSelect<false> | PartenairesSelect<true>;
    'licences-packs': LicencesPacksSelect<false> | LicencesPacksSelect<true>;
    'licences-activations': LicencesActivationsSelect<false> | LicencesActivationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'types-evenement': TypesEvenementSelect<false> | TypesEvenementSelect<true>;
    badges: BadgesSelect<false> | BadgesSelect<true>;
    groupes: GroupesSelect<false> | GroupesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'stripe-events': StripeEventsSelect<false> | StripeEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'reseauteur' | 'organisateur' | 'partenaire' | 'admin';
  /**
   * [DORMANT — ADR-0011] Ancien champ de plan. Sera supprimé par accounts-and-billing (J2.A).
   */
  plan?: string | null;
  /**
   * [ADR-0013] Réseauteur Plus actif (droit de créer des événements). Posé par webhook/serveur.
   */
  plusActif?: boolean | null;
  /**
   * [ADR-0013] Expiration du Plus (fin d'abonnement ou du pack de licences).
   */
  plusExpireAt?: string | null;
  /**
   * [ADR-0013] Origine du Plus : "abonnement" (Stripe individuel). "licence" = legacy (packs partenaires supprimés — ADR-0015).
   */
  plusSource?: string | null;
  /**
   * [Dormant — ADR-0015] Pack de licences legacy dont provient le Plus (si plusSource = licence).
   */
  plusLicencePack?: (number | null) | LicencesPack;
  /**
   * Groupe d'affiliation (optionnel)
   */
  groupe?: (number | null) | Groupe;
  /**
   * Code d'invitation memorise au signup pour un user gratuit, applique automatiquement au passage en Infinite (webhook checkout.session.completed). Vide une fois consomme.
   */
  pendingGroupeCode?: string | null;
  nomSociete: string;
  ville: string;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  planExpiresAt?: string | null;
  /**
   * Emails de la sequence d'onboarding deja envoyes a ce compte.
   */
  onboardingEmails?: {
    welcomeSent?: boolean | null;
    j3Sent?: boolean | null;
    j7Sent?: boolean | null;
    j14Sent?: boolean | null;
  };
  /**
   * Alertes d'expiration d'abonnement deja envoyees (J-30, J-7). Flag remis a false lors du renouvellement.
   */
  expirationAlerts?: {
    j30Sent?: boolean | null;
    j7Sent?: boolean | null;
  };
  /**
   * Date d'acceptation des CGU (horodatage du consentement).
   */
  cguAcceptedAt?: string | null;
  /**
   * Date d'acceptation de la politique de confidentialite.
   */
  confidentialiteAcceptedAt?: string | null;
  /**
   * Consentement marketing — filtre l'envoi des emails J3/J7/J14.
   */
  optInMarketing?: boolean | null;
  /**
   * Date du consentement aux emails marketing.
   */
  optInMarketingAt?: string | null;
  /**
   * Date de revocation du consentement marketing (preuve).
   */
  optOutMarketingAt?: string | null;
  /**
   * Adresse de facturation telle que renseignee dans Stripe Checkout.
   */
  billingAddress?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Numero de TVA intracommunautaire (facturation B2B).
   */
  vatNumber?: string | null;
  /**
   * Raison sociale utilisee pour la facturation Stripe.
   */
  raisonSocialeFacturation?: string | null;
  /**
   * Auto-positionne sur hard bounce / spam complaint (webhook Resend). Bloque tout envoi sortant vers cet email.
   */
  emailBlacklisted?: boolean | null;
  /**
   * Raison du blacklist (positionnee par le webhook Resend).
   */
  emailBlacklistedReason?: ('hard-bounce' | 'complaint') | null;
  /**
   * Date du blacklist.
   */
  emailBlacklistedAt?: string | null;
  /**
   * Cocher pour exclure ce compte de la sequence d'onboarding (welcome rattrapage + J+3/J+7/J+14). Usage : comptes de test internes, demos, ou comptes admin qui ne doivent pas recevoir le parcours nudge.
   */
  excludeFromOnboarding?: boolean | null;
  /**
   * Nouvelle adresse en attente de confirmation via le lien envoye par /api/account/change-email.
   */
  pendingEmail?: string | null;
  /**
   * SHA-256(token + PAYLOAD_SECRET) du lien de confirmation — jamais le token brut.
   */
  pendingEmailTokenHash?: string | null;
  /**
   * Expiration du lien de confirmation de changement d'email (24h).
   */
  pendingEmailExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * [Dormant — ADR-0015] Packs de licences legacy (fonctionnalité supprimée, extinction par cron).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licences-packs".
 */
export interface LicencesPack {
  id: number;
  /**
   * Partenaire propriétaire du pack.
   */
  partenaire: number | Partenaire;
  /**
   * Nombre de licences du pack (10 / 50 / 100 — gate P0 D2).
   */
  quota: number;
  /**
   * Licences déjà activées. Incrémenté transactionnellement par la route d'activation.
   */
  quotaUtilise?: number | null;
  /**
   * Code promo à diffuser aux réseauteurs. Généré serveur à la création.
   */
  code?: string | null;
  /**
   * Posé par le webhook (achat), la route d'activation (épuisement) et le cron (expiration).
   */
  statut: 'actif' | 'epuise' | 'expire';
  /**
   * Expiration du pack (alignée sur l'abonnement annonceur — gate P0 D4). Reconduction au rachat.
   */
  expireAt?: string | null;
  /**
   * Session Checkout one-shot du paiement du pack.
   */
  stripeCheckoutSessionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Annonceurs B2B — logo page d'accueil + page Partenaires + fiche perso.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partenaires".
 */
export interface Partenaire {
  id: number;
  /**
   * Compte propriétaire (1 user = 1 partenaire).
   */
  user?: (number | null) | User;
  /**
   * Généré depuis le nom à la création ; figé ensuite (URL /partenaire/<slug>).
   */
  slug?: string | null;
  nom: string;
  /**
   * Logo affiché sur la page d'accueil, la page Partenaires et votre fiche (fond clair, carré recommandé).
   */
  logo?: (number | null) | Media;
  /**
   * Lien vers votre site (s'ouvre dans un nouvel onglet).
   */
  lien?: string | null;
  /**
   * Une phrase de présentation affichée sur la page Partenaires et votre fiche.
   */
  description?: string | null;
  /**
   * Offre promotionnelle visible UNIQUEMENT par les réseauteurs connectés. Laissez le titre vide pour ne pas proposer d'offre.
   */
  offre?: {
    titre?: string | null;
    description?: string | null;
    lien?: string | null;
  };
  /**
   * Statut d'abonnement. Posé automatiquement par le webhook Stripe.
   */
  statut: 'actif' | 'expire';
  /**
   * Customer Stripe rattaché.
   */
  stripeCustomerId?: string | null;
  /**
   * ID de l'abonnement Stripe.
   */
  stripeSubscriptionId?: string | null;
  /**
   * Date d'expiration de l'abonnement.
   */
  abonnementExpireAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groupes".
 */
export interface Groupe {
  id: number;
  nom: string;
  /**
   * Code d'affiliation pour rejoindre le groupe (auto-genere)
   */
  code: string;
  owner: number | User;
  /**
   * Palier de reduction actif (calcule automatiquement)
   */
  palierActuel: '0' | '5' | '10' | '15';
  /**
   * ID du coupon Stripe applique au groupe
   */
  stripeCouponId?: string | null;
  /**
   * Soft-delete : un groupe deletedAt != null n'est plus joignable par code et n'apparait plus pour ses membres. Conservation pour audit.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Personnes inscrites sur la plateforme (profil public, carte des réseauteurs).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reseauteurs".
 */
export interface Reseauteur {
  id: number;
  /**
   * Compte propriétaire (1 user = 1 réseauteur).
   */
  user?: (number | null) | User;
  /**
   * Généré depuis prénom+nom à la création ; figé ensuite (contrat SEO — ADR-0005).
   */
  slug?: string | null;
  prenom?: string | null;
  nom: string;
  photo?: (number | null) | Media;
  fonction?: string | null;
  entreprise?: string | null;
  /**
   * Description libre affichée sur la fiche publique.
   */
  description?: string | null;
  /**
   * Laissez vide pour ne pas partager votre téléphone.
   */
  telephone?: string | null;
  /**
   * Laissez vide pour ne pas partager votre email publiquement.
   */
  emailContact?: string | null;
  site?: string | null;
  /**
   * URL complète de votre profil LinkedIn.
   */
  linkedin?: string | null;
  ville: string;
  /**
   * Ex : Puy-de-Dôme, Rhône, Paris.
   */
  departement?: string | null;
  /**
   * Ex : Auvergne-Rhône-Alpes, Île-de-France.
   */
  region?: string | null;
  /**
   * Secteur principal du réseauteur.
   */
  secteur?: (number | null) | Category;
  /**
   * Compétences clés (max 20). Utilisées pour la recherche par profil.
   */
  competences?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Réseaux d'affaires que vous fréquentez — réseau national (ex : BNI France) ou groupe local (ex : DCF Lyon). Multi-sélection.
   */
  reseauxFrequentes?: (number | Reseau)[] | null;
  /**
   * [Dormant — ADR-0014] Ancien mécanisme « admin déclaré », remplacé par la propriété des réseaux locaux (reseaux.user).
   */
  adminReseaux?: (number | Reseau)[] | null;
  /**
   * Événements des réseaux que vous fréquentez auxquels vous signalez votre présence. Affiché sur votre fiche publique et sur la fiche de chaque événement.
   */
  evenementsParticipes?: (number | Evenement)[] | null;
  /**
   * Question obligatoire à l'inscription. Détermine votre badge (Bronze/Argent/Gold/Platinum).
   */
  evenementsParMois: number;
  /**
   * Auto-dérivé depuis "événements par mois". Ne pas modifier manuellement sauf exception.
   */
  badge?: ('bronze' | 'argent' | 'gold' | 'platinum') | null;
  /**
   * Latitude du centroïde ville (auto-calculée par géocodage).
   */
  latitude?: number | null;
  /**
   * Longitude du centroïde ville (auto-calculée par géocodage).
   */
  longitude?: number | null;
  /**
   * Statut de modération. Seuls les profils validés sont visibles sur la carte et dans le sitemap.
   */
  statut: 'en_attente' | 'valide' | 'suspendu';
  /**
   * Champs SEO optionnels. Laissez vide pour utiliser les valeurs par defaut calculees depuis la fiche.
   */
  seo?: {
    /**
     * Meta title (60 car. recommandes). Fallback : nom de l'entite.
     */
    title?: string | null;
    /**
     * Meta description (160 car. max). Fallback : description de la fiche.
     */
    description?: string | null;
    /**
     * Mots-cles separes par des virgules (optionnel, peu utile en 2026).
     */
    keywords?: string | null;
    /**
     * Image partagee sur les reseaux sociaux. Fallback : banniere puis logo.
     */
    ogImage?: (number | null) | Media;
    /**
     * Cochez pour empecher cette page d'etre indexee par les moteurs de recherche.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Secteurs d'activité / métiers des réseauteurs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Ex : BTP, Santé, Finance, Tech, Commerce…
   */
  label: string;
  /**
   * Identifiant technique, ex : btp, sante, finance.
   */
  value: string;
  /**
   * Code couleur hexadécimal, ex : #1e40af.
   */
  couleur?: string | null;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reseaux".
 */
export interface Reseau {
  id: number;
  /**
   * Compte propriétaire (vide pour les fiches orphelines non revendiquées).
   */
  user?: (number | null) | User;
  /**
   * Provenance du réseau. "Revendiqué" = propriétaire actif ; "Importé" = fiche importée revendiquable.
   */
  source: 'revendique' | 'importe';
  /**
   * Échelle du réseau. Régional/National/International = tête de réseau (abonnement + groupes) ; Local = groupe rattaché à une tête.
   */
  niveau: 'local' | 'regional' | 'national' | 'international';
  /**
   * Tête de réseau parente (facultatif — laissez vide pour un réseau local indépendant).
   */
  parent?: (number | null) | Reseau;
  /**
   * [Significatif sur une tête de réseau uniquement] Palier d'abonnement déterminant le nombre max de locaux. Posé par le webhook Stripe après souscription. ⚠️ Valeurs placeholder — seuils/prix réels à configurer avant E2.A.
   */
  palier?: ('fiche' | 'starter' | 'growth' | 'enterprise') | null;
  /**
   * Généré depuis le nom à la création ; figé ensuite (contrat SEO).
   */
  slug?: string | null;
  nom: string;
  ville?: string | null;
  adresse?: string | null;
  codePostal?: string | null;
  /**
   * Ex : Rhône, Paris, Gironde.
   */
  departement?: string | null;
  /**
   * Ex : Auvergne-Rhône-Alpes, Île-de-France.
   */
  region?: string | null;
  /**
   * Nature juridique du réseau.
   */
  typeJuridique?: ('association' | 'prive' | 'franchise' | 'institution' | 'autre') | null;
  /**
   * Catégorie principale du réseau (Réseaux d'affaires, Afterworks, Congrès…).
   */
  categorie?: (number | null) | TypesEvenement;
  /**
   * Description courte du réseau (sans limite de longueur).
   */
  description?: string | null;
  logo?: (number | null) | Media;
  banniere?: (number | null) | Media;
  illustrations?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Lien vers la plaquette de présentation (PDF hébergé). Le média interne n'accepte que des images.
   */
  plaquetteUrl?: string | null;
  siteWeb?: string | null;
  emailContact?: string | null;
  telephone?: string | null;
  responsableNom?: string | null;
  responsableFonction?: string | null;
  responsablePhoto?: (number | null) | Media;
  /**
   * Lien vers une vidéo YouTube (ex: https://www.youtube.com/watch?v=xxx).
   */
  videoYoutube?: string | null;
  reseauxSociaux?:
    | {
        plateforme: 'facebook' | 'instagram' | 'linkedin' | 'twitter' | 'youtube' | 'tiktok' | 'pinterest';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Latitude (auto-calculée par géocodage).
   */
  latitude?: number | null;
  /**
   * Longitude (auto-calculée par géocodage).
   */
  longitude?: number | null;
  /**
   * Texte de présentation complet du réseau (affiché sur la fiche publique).
   */
  presentation?: string | null;
  objectif?: string | null;
  /**
   * Ce qui distingue ce réseau des autres (3 à 5 lignes).
   */
  differenciateur?: string | null;
  /**
   * Nombre de membres déclaré par le réseau — distinct du compteur « nbReseauteurs » (réseauteurs de la plateforme).
   */
  nombreMembres?: number | null;
  /**
   * Ex : dirigeants, entrepreneurs, indépendants, commerciaux…
   */
  publicConcerne?: string | null;
  ouvertATous?: ('oui' | 'non') | null;
  participationInvite?: ('oui' | 'non') | null;
  adhesionObligatoire?: ('oui' | 'non') | null;
  uneProfessionParGroupe?: ('oui' | 'non') | null;
  /**
   * Ex : « à partir de 400 €/an » — texte libre.
   */
  cotisation?: string | null;
  /**
   * [Significatif sur le national uniquement — ADR-0012] Abonnement partenaire actif. Débloque : création de locaux, publication d'événements, badge partenaire, logo page d'accueil. Posé par webhook Stripe. Inerte sur un local.
   */
  partenaire?: boolean | null;
  /**
   * [Significatif sur le national uniquement — ADR-0012] ID de l'abonnement Stripe partenaire. Géré par accounts-and-billing. Inerte sur un local.
   */
  stripeSubscriptionId?: string | null;
  /**
   * [Significatif sur le national uniquement — ADR-0012] Date d'expiration du partenariat. Inerte sur un local.
   */
  partenaireExpireAt?: string | null;
  /**
   * Nombre de réseauteurs validés qui fréquentent ce réseau (auto-calculé).
   */
  nbReseauteurs?: number | null;
  /**
   * Nombre d'événements publiés pour ce réseau (auto-calculé).
   */
  nbEvenements?: number | null;
  /**
   * Statut de visibilité publique du réseau.
   */
  statut: 'publiee' | 'suspendue';
  /**
   * Nom de la personne ayant renseigné/mis à jour la fiche (traçabilité).
   */
  rempliPar?: string | null;
  /**
   * Champs SEO optionnels. Laissez vide pour utiliser les valeurs par defaut calculees depuis la fiche.
   */
  seo?: {
    /**
     * Meta title (60 car. recommandes). Fallback : nom de l'entite.
     */
    title?: string | null;
    /**
     * Meta description (160 car. max). Fallback : description de la fiche.
     */
    description?: string | null;
    /**
     * Mots-cles separes par des virgules (optionnel, peu utile en 2026).
     */
    keywords?: string | null;
    /**
     * Image partagee sur les reseaux sociaux. Fallback : banniere puis logo.
     */
    ogImage?: (number | null) | Media;
    /**
     * Cochez pour empecher cette page d'etre indexee par les moteurs de recherche.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types-evenement".
 */
export interface TypesEvenement {
  id: number;
  label: string;
  /**
   * Identifiant technique, ex: salon
   */
  value: string;
  /**
   * Code couleur hexadecimal, ex: #1e40af
   */
  couleur: string;
  ordre?: number | null;
  /**
   * Champs SEO optionnels. Laissez vide pour utiliser les valeurs par defaut calculees depuis la fiche.
   */
  seo?: {
    /**
     * Meta title (60 car. recommandes). Fallback : nom de l'entite.
     */
    title?: string | null;
    /**
     * Meta description (160 car. max). Fallback : description de la fiche.
     */
    description?: string | null;
    /**
     * Mots-cles separes par des virgules (optionnel, peu utile en 2026).
     */
    keywords?: string | null;
    /**
     * Image partagee sur les reseaux sociaux. Fallback : banniere puis logo.
     */
    ogImage?: (number | null) | Media;
    /**
     * Cochez pour empecher cette page d'etre indexee par les moteurs de recherche.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements".
 */
export interface Evenement {
  id: number;
  /**
   * Généré depuis le titre à la création ; figé ensuite (contrat SEO — ADR-0005).
   */
  slug?: string | null;
  /**
   * Réseau qui organise cet événement (exclusif avec « Réseauteur organisateur »).
   */
  reseau?: (number | null) | Reseau;
  /**
   * [ADR-0013] Réseauteur Plus qui organise cet événement (exclusif avec « Réseau organisateur »).
   */
  organisateurReseauteur?: (number | null) | Reseauteur;
  titre: string;
  type: number | TypesEvenement;
  /**
   * Date et heure de début de l'événement.
   */
  dateDebut: string;
  dateFin?: string | null;
  lieuNom?: string | null;
  lieuAdresse?: string | null;
  lieuCodePostal?: string | null;
  lieuVille: string;
  /**
   * Ex : Rhône, Paris, Gironde. Utilisé pour le filtre par département.
   */
  lieuDepartement?: string | null;
  /**
   * Résumé affiché en tête de fiche et dans les listes.
   */
  descriptionCourte?: string | null;
  description?: string | null;
  /**
   * Nom(s) et qualité des intervenants (si applicable).
   */
  intervenants?: string | null;
  /**
   * URL vers le site ou formulaire d'inscription du réseau organisateur. Le bouton « S'inscrire » redirige vers ce lien.
   */
  lienInscription?: string | null;
  contactNom?: string | null;
  contactEmail?: string | null;
  contactTelephone?: string | null;
  image?: (number | null) | Media;
  galerie?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex : entrepreneurs, dirigeants, indépendants, commerciaux, étudiants, tous…
   */
  publicConcerne?: string | null;
  /**
   * Secteur principal concerné (facultatif).
   */
  secteur?: (number | null) | Category;
  niveauPublic?: ('debutant' | 'confirme' | 'tous') | null;
  /**
   * Décochez si l'événement est payant, puis renseignez le tarif.
   */
  gratuit?: boolean | null;
  /**
   * Ex : « 25 € », « gratuit pour les membres, 15 € invités ». Affiché si l'événement est payant.
   */
  tarif?: string | null;
  nombrePlaces?: number | null;
  dateLimiteInscription?: string | null;
  ouvertATous?: ('oui' | 'non') | null;
  reserveMembres?: ('oui' | 'non') | null;
  participationInvite?: ('oui' | 'non') | null;
  parking?: boolean | null;
  accesPmr?: boolean | null;
  infosPratiques?: string | null;
  /**
   * Statut de visibilité de l'événement.
   */
  statut: 'publie' | 'suspendu';
  /**
   * Nom de la personne ayant créé l'événement (traçabilité).
   */
  creePar?: string | null;
  /**
   * Compte ayant créé l'événement (figé serveur à la création). Ownership des événements de groupe créés par un réseauteur Plus admin déclaré (décision 2026-07-16).
   */
  creeParUser?: (number | null) | User;
  /**
   * Latitude (auto-calculée par géocodage).
   */
  lieuLatitude?: number | null;
  /**
   * Longitude (auto-calculée par géocodage).
   */
  lieuLongitude?: number | null;
  /**
   * Champs SEO optionnels. Laissez vide pour utiliser les valeurs par defaut calculees depuis la fiche.
   */
  seo?: {
    /**
     * Meta title (60 car. recommandes). Fallback : nom de l'entite.
     */
    title?: string | null;
    /**
     * Meta description (160 car. max). Fallback : description de la fiche.
     */
    description?: string | null;
    /**
     * Mots-cles separes par des virgules (optionnel, peu utile en 2026).
     */
    keywords?: string | null;
    /**
     * Image partagee sur les reseaux sociaux. Fallback : banniere puis logo.
     */
    ogImage?: (number | null) | Media;
    /**
     * Cochez pour empecher cette page d'etre indexee par les moteurs de recherche.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Inscriptions des réseauteurs aux événements organisés par des réseauteurs Plus (ADR-0013).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscriptions".
 */
export interface Inscription {
  id: number;
  /**
   * Événement (organisé par un réseauteur Plus).
   */
  evenement: number | Evenement;
  /**
   * Réseauteur inscrit (une inscription par événement).
   */
  reseauteur: number | Reseauteur;
  updatedAt: string;
  createdAt: string;
}
/**
 * [Dormant — ADR-0015] Traçabilité legacy des activations (fonctionnalité supprimée).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licences-activations".
 */
export interface LicencesActivation {
  id: number;
  /**
   * Pack dont provient la licence.
   */
  pack: number | LicencesPack;
  /**
   * Réseauteur ayant activé la licence (une seule activation par compte).
   */
  user: number | User;
  /**
   * Date d'activation.
   */
  activeAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Référentiel des badges réseauteur (libellés, icônes). La dérivation reste dans lib/badge.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges".
 */
export interface Badge {
  id: number;
  /**
   * Identifiant technique du badge (correspond à reseauteurs.badge).
   */
  niveau: 'bronze' | 'argent' | 'gold' | 'platinum';
  /**
   * Ex : Bronze, Argent, Gold, Platinum.
   */
  label: string;
  /**
   * Explication du badge pour les visiteurs (ex : « Fréquente 2 à 5 événements/mois »).
   */
  description?: string | null;
  /**
   * Icône SVG ou PNG affiché sur le profil et les marqueurs de carte.
   */
  icone?: (number | null) | Media;
  /**
   * Code couleur hexadécimal, ex : #CD7F32 (bronze).
   */
  couleur?: string | null;
  /**
   * Nombre minimum d'événements/mois pour ce badge.
   */
  seuilMin: number;
  /**
   * Nombre maximum d'événements/mois (laisser vide pour Platinum).
   */
  seuilMax?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  company?: string | null;
  logo?: (number | null) | Media;
  rating: number;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Journal d'audit RGPD (anonymise). Preuve de conformite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  type:
    | 'account_deleted'
    | 'consent_given'
    | 'consent_revoked'
    | 'data_exported'
    | 'stripe_misconfig'
    | 'groupe_sync_failed'
    | 'plan_changed'
    | 'groupe_soft_deleted'
    | 'email_changed'
    | 'groupe_created'
    | 'groupe_joined'
    | 'groupe_left'
    | 'groupe_ownership_transferred'
    | 'email_blacklisted'
    | 'national_invited';
  /**
   * SHA-256(userId + PAYLOAD_SECRET) — anonymise.
   */
  userIdHash: string;
  /**
   * Contexte non-identifiant (plan, raison, palier, etc.).
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Journal des événements Stripe traités (idempotence webhook).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-events".
 */
export interface StripeEvent {
  id: number;
  /**
   * Identifiant Stripe de l'event (evt_...).
   */
  eventId: string;
  type?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'reseauteurs';
        value: number | Reseauteur;
      } | null)
    | ({
        relationTo: 'reseaux';
        value: number | Reseau;
      } | null)
    | ({
        relationTo: 'evenements';
        value: number | Evenement;
      } | null)
    | ({
        relationTo: 'inscriptions';
        value: number | Inscription;
      } | null)
    | ({
        relationTo: 'partenaires';
        value: number | Partenaire;
      } | null)
    | ({
        relationTo: 'licences-packs';
        value: number | LicencesPack;
      } | null)
    | ({
        relationTo: 'licences-activations';
        value: number | LicencesActivation;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'types-evenement';
        value: number | TypesEvenement;
      } | null)
    | ({
        relationTo: 'badges';
        value: number | Badge;
      } | null)
    | ({
        relationTo: 'groupes';
        value: number | Groupe;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'stripe-events';
        value: number | StripeEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  plan?: T;
  plusActif?: T;
  plusExpireAt?: T;
  plusSource?: T;
  plusLicencePack?: T;
  groupe?: T;
  pendingGroupeCode?: T;
  nomSociete?: T;
  ville?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  planExpiresAt?: T;
  onboardingEmails?:
    | T
    | {
        welcomeSent?: T;
        j3Sent?: T;
        j7Sent?: T;
        j14Sent?: T;
      };
  expirationAlerts?:
    | T
    | {
        j30Sent?: T;
        j7Sent?: T;
      };
  cguAcceptedAt?: T;
  confidentialiteAcceptedAt?: T;
  optInMarketing?: T;
  optInMarketingAt?: T;
  optOutMarketingAt?: T;
  billingAddress?: T;
  vatNumber?: T;
  raisonSocialeFacturation?: T;
  emailBlacklisted?: T;
  emailBlacklistedReason?: T;
  emailBlacklistedAt?: T;
  excludeFromOnboarding?: T;
  pendingEmail?: T;
  pendingEmailTokenHash?: T;
  pendingEmailExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reseauteurs_select".
 */
export interface ReseauteursSelect<T extends boolean = true> {
  user?: T;
  slug?: T;
  prenom?: T;
  nom?: T;
  photo?: T;
  fonction?: T;
  entreprise?: T;
  description?: T;
  telephone?: T;
  emailContact?: T;
  site?: T;
  linkedin?: T;
  ville?: T;
  departement?: T;
  region?: T;
  secteur?: T;
  competences?:
    | T
    | {
        label?: T;
        id?: T;
      };
  reseauxFrequentes?: T;
  adminReseaux?: T;
  evenementsParticipes?: T;
  evenementsParMois?: T;
  badge?: T;
  latitude?: T;
  longitude?: T;
  statut?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reseaux_select".
 */
export interface ReseauxSelect<T extends boolean = true> {
  user?: T;
  source?: T;
  niveau?: T;
  parent?: T;
  palier?: T;
  slug?: T;
  nom?: T;
  ville?: T;
  adresse?: T;
  codePostal?: T;
  departement?: T;
  region?: T;
  typeJuridique?: T;
  categorie?: T;
  description?: T;
  logo?: T;
  banniere?: T;
  illustrations?:
    | T
    | {
        image?: T;
        id?: T;
      };
  plaquetteUrl?: T;
  siteWeb?: T;
  emailContact?: T;
  telephone?: T;
  responsableNom?: T;
  responsableFonction?: T;
  responsablePhoto?: T;
  videoYoutube?: T;
  reseauxSociaux?:
    | T
    | {
        plateforme?: T;
        url?: T;
        id?: T;
      };
  latitude?: T;
  longitude?: T;
  presentation?: T;
  objectif?: T;
  differenciateur?: T;
  nombreMembres?: T;
  publicConcerne?: T;
  ouvertATous?: T;
  participationInvite?: T;
  adhesionObligatoire?: T;
  uneProfessionParGroupe?: T;
  cotisation?: T;
  partenaire?: T;
  stripeSubscriptionId?: T;
  partenaireExpireAt?: T;
  nbReseauteurs?: T;
  nbEvenements?: T;
  statut?: T;
  rempliPar?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenements_select".
 */
export interface EvenementsSelect<T extends boolean = true> {
  slug?: T;
  reseau?: T;
  organisateurReseauteur?: T;
  titre?: T;
  type?: T;
  dateDebut?: T;
  dateFin?: T;
  lieuNom?: T;
  lieuAdresse?: T;
  lieuCodePostal?: T;
  lieuVille?: T;
  lieuDepartement?: T;
  descriptionCourte?: T;
  description?: T;
  intervenants?: T;
  lienInscription?: T;
  contactNom?: T;
  contactEmail?: T;
  contactTelephone?: T;
  image?: T;
  galerie?:
    | T
    | {
        image?: T;
        id?: T;
      };
  publicConcerne?: T;
  secteur?: T;
  niveauPublic?: T;
  gratuit?: T;
  tarif?: T;
  nombrePlaces?: T;
  dateLimiteInscription?: T;
  ouvertATous?: T;
  reserveMembres?: T;
  participationInvite?: T;
  parking?: T;
  accesPmr?: T;
  infosPratiques?: T;
  statut?: T;
  creePar?: T;
  creeParUser?: T;
  lieuLatitude?: T;
  lieuLongitude?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscriptions_select".
 */
export interface InscriptionsSelect<T extends boolean = true> {
  evenement?: T;
  reseauteur?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partenaires_select".
 */
export interface PartenairesSelect<T extends boolean = true> {
  user?: T;
  slug?: T;
  nom?: T;
  logo?: T;
  lien?: T;
  description?: T;
  offre?:
    | T
    | {
        titre?: T;
        description?: T;
        lien?: T;
      };
  statut?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  abonnementExpireAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licences-packs_select".
 */
export interface LicencesPacksSelect<T extends boolean = true> {
  partenaire?: T;
  quota?: T;
  quotaUtilise?: T;
  code?: T;
  statut?: T;
  expireAt?: T;
  stripeCheckoutSessionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licences-activations_select".
 */
export interface LicencesActivationsSelect<T extends boolean = true> {
  pack?: T;
  user?: T;
  activeAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  couleur?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types-evenement_select".
 */
export interface TypesEvenementSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  couleur?: T;
  ordre?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges_select".
 */
export interface BadgesSelect<T extends boolean = true> {
  niveau?: T;
  label?: T;
  description?: T;
  icone?: T;
  couleur?: T;
  seuilMin?: T;
  seuilMax?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groupes_select".
 */
export interface GroupesSelect<T extends boolean = true> {
  nom?: T;
  code?: T;
  owner?: T;
  palierActuel?: T;
  stripeCouponId?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  company?: T;
  logo?: T;
  rating?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  type?: T;
  userIdHash?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-events_select".
 */
export interface StripeEventsSelect<T extends boolean = true> {
  eventId?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}